spring:
  application:
    name: liangyoudemo
  profiles:
    active: dev
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

server:
  port: 8080

knife4j:
  enable: true
  setting:
    language: zh_cn
